services:
  tfaco2-mqtt:
    image: ghcr.io/buliwyf42/tfaco2-mqtt-bridge:latest
    container_name: tfaco2-mqtt
    restart: unless-stopped
    env_file:
      - .env
    devices:
      - "/dev/hidraw0:/dev/hidraw0"
    environment:
      DEVICE_PATH: /dev/hidraw0
